Repository TeamFILL-IN/Fill-Android, pull requests merged in 2022-03, with the labels that each got.

#83 [Feature/#77] StudioMap 리팩토링
  app/src/main/java/com/teamfillin/fillin/config/di/RepositoryModule.kt
  app/src/main/java/com/teamfillin/fillin/data/repository/StudioMapRepositoryImpl.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseStudio.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseStudioLocation.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseStudioPhoto.kt
  app/src/main/java/com/teamfillin/fillin/domain/entity/StudioDetail.kt
  app/src/main/java/com/teamfillin/fillin/domain/entity/StudioImage.kt
  app/src/main/java/com/teamfillin/fillin/domain/entity/StudioMap.kt
  app/src/main/java/com/teamfillin/fillin/domain/repository/StudioMapRepository.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/PhotoReviewListAdapter.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/StudioMapActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/StudioMapViewModel.kt
  app/src/main/res/layout/fragment_photo_dialog.xml
  core/src/main/java/com/teamfillin/fillin/core/content/Event.kt
  core/src/main/java/com/teamfillin/fillin/core/content/EventObserver.kt
Labels: refactor :recycle:, 강민 🦖

#81 [feature/#79] 앱 난독화 및 리소스 최적화 옵션 적용
  .gitignore
  README.md
  app/build.gradle.kts
  app/proguard-rules.pro
  app/release/output-metadata.json
  app/src/debug/res/values/strings.xml
  app/src/main/java/com/teamfillin/fillin/config/di/RetrofitModule.kt
  app/src/main/java/com/teamfillin/fillin/config/initializer/KakaoAuthInitializer.kt
  app/src/main/java/com/teamfillin/fillin/config/initializer/TimberInitializer.kt
  app/src/main/java/com/teamfillin/fillin/data/repository/MapSearchRepositoryImpl.kt
  app/src/main/java/com/teamfillin/fillin/data/response/BaseResponse.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseAuth.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseFilmRoll.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseFilmStyleInfo.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseFilmType.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseLocationInfo.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseNewPhotoInfo.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseRefresh.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseSearch.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseStudio.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseStudioLocation.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseStudioPhoto.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseUserInfo.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseUserPhotoInfo.kt
  app/src/main/java/com/teamfillin/fillin/data/response/experimental/PhotoDto.kt
  app/src/main/java/com/teamfillin/fillin/data/service/AuthService.kt
  app/src/main/java/com/teamfillin/fillin/data/service/UserService.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/FilmRollActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/login/LoginActivity.kt
  app/src/main/res/layout/activity_login.xml
  buildSrc/src/main/kotlin/Constants.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  core/build.gradle.kts
  core/proguard-rules.pro
  core/src/main/java/com/teamfillin/fillin/core/converter/JsonConverterFactory.kt
  core/src/main/java/com/teamfillin/fillin/core/converter/KotlinSerialization.kt
Labels: refactor :recycle:, 누누 ⛄️

#86 [feature/clipboard_idkey] Debug 모드에서 카카오 idKey까지 복사할 수 있게 만들기
  app/src/main/java/com/teamfillin/fillin/presentation/my/MyPageActivity.kt
Labels: feature :bulb:, 누누 ⛄️
