Repository TeamFILL-IN/Fill-Android, pull requests merged in 2022-02, with the labels that each got.

#66 [feature/server_refresh_token] 디버그 모드에서 카카오 accessToken 채취할 수 있는 기능 추가
  app/src/main/java/com/teamfillin/fillin/presentation/my/MyPageActivity.kt
  app/src/main/res/layout/activity_my_page.xml
Labels: feature :bulb:

#67 [Feature/#63] MapSearch 리팩토링
  app/src/main/java/com/teamfillin/fillin/config/di/RepositoryModule.kt
  app/src/main/java/com/teamfillin/fillin/data/repository/MapSearchRepositoryImpl.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseSearch.kt
  app/src/main/java/com/teamfillin/fillin/domain/entity/StudioSearch.kt
  app/src/main/java/com/teamfillin/fillin/domain/repository/MapSearchRepository.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/MapSearchActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/MapSearchViewModel.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/SearchListAdapter.kt
  app/src/main/res/layout/item_location_info.xml
  core/src/main/java/com/teamfillin/fillin/core/content/SingleLiveEvent.kt
Labels: refactor :recycle:, 강민 🦖

#73 [feature/#72] 안쓰는 이미지 삭제
  app/src/main/res/drawable-hdpi/and_photo_rectangle.png
  app/src/main/res/drawable-hdpi/and_photoframe.png
  app/src/main/res/drawable-mdpi/and_photo_rectangle.png
  app/src/main/res/drawable-mdpi/and_photoframe.png
  app/src/main/res/drawable-v24/unlike.png
  app/src/main/res/drawable-xhdpi/and_photo_rectangle.png
  app/src/main/res/drawable-xhdpi/and_photoframe.png
  app/src/main/res/drawable-xxhdpi/and_photo_rectangle.png
  app/src/main/res/drawable-xxhdpi/and_photoframe.png
  app/src/main/res/drawable-xxxhdpi/and_photo_rectangle.png
  app/src/main/res/drawable-xxxhdpi/and_photoframe.png
  app/src/main/res/layout/fragment_photo_dialog.xml
  app/src/main/res/layout/item_category_image.xml
  app/src/main/res/layout/item_film_roll_pic.xml
  app/src/main/res/layout/item_my_page.xml
  app/src/main/res/layout/item_new_photos_list.xml
  app/src/main/res/layout/item_photo_review.xml
Labels: 수빈🍍

#74 [feature/#71] 마이페이지 디폴트 이미지 수정
  app/src/main/java/com/teamfillin/fillin/presentation/my/MyPageActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/my/MyPagePhotoRecyclerViewAdapter.kt
Labels: feature :bulb:, 현지 🛌🏻

#76 [feature/#75] FilmRoll 화면에서 사진 클릭 시 사진 다이얼로그 제대로 뜰 수 있게 수정
  app/src/main/java/com/teamfillin/fillin/domain/entity/Photo.kt
  app/src/main/java/com/teamfillin/fillin/presentation/dialog/PhotoDialogFragment.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/CurationAdapter.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/FilmRollActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/FilmRollAdapter.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/FilmRollPagingAdapter.kt
  app/src/main/java/com/teamfillin/fillin/presentation/home/HomeActivity.kt
  app/src/main/res/layout/activity_film_roll.xml
  app/src/main/res/layout/fragment_photo_dialog.xml
  app/src/main/res/layout/item_curation.xml
  app/src/main/res/layout/item_curation_first.xml
  app/src/main/res/layout/item_film_roll.xml
  core/build.gradle.kts
  core/src/main/java/com/teamfillin/fillin/core/content/RetrofitUtil.kt
  core/src/main/java/com/teamfillin/fillin/core/intent/ArgsExt.kt
Labels: bug :bug:, 누누 ⛄️
