Repository TeamFILL-IN/Fill-Android, pull requests merged in 2022-01, with the labels that each got.

#1 [feature/github_setting] Github 기본 템플릿 설정
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pr_checker.yml
  buildSrc/src/main/kotlin/Versions.kt
Labels: feature :bulb:

#4 Feature/#3
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamfillin/fillin/App.kt
  app/src/main/java/com/teamfillin/fillin/config/initializer/TimberInitializer.kt
Labels: feature :bulb:

#7 [feature/#5] Flipper 설정하기
  app/src/debug/java/com/teamfillin/fillin/FlipperInitializer.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamfillin/fillin/App.kt
  app/src/main/java/com/teamfillin/fillin/presentation/HomeActivity.kt
  app/src/main/res/layout/activity_home.xml
  app/src/release/java/com/teamfillin/fillin/FlipperInitializer.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: feature :bulb:

#11 [feature/#9] 아이콘 및 이미지 세팅
  app/src/main/res/drawable/ic_addphoto.xml
  app/src/main/res/drawable/ic_addphoto_default.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_filmroll.xml
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/drawable/ic_mypage.xml
  app/src/main/res/drawable/ic_place_big.xml
  app/src/main/res/drawable/ic_stduiomap.xml
Labels: feature :bulb:

#13 [feature/#8] Kakao Login 클라이언트 단에서 구현
  .gitignore
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamfillin/fillin/config/di/LoginModule.kt
  app/src/main/java/com/teamfillin/fillin/config/initializer/KakaoAuthInitializer.kt
  app/src/main/java/com/teamfillin/fillin/presentation/HomeActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/login/KakaoAuthService.kt
  app/src/main/java/com/teamfillin/fillin/presentation/login/LoginActivity.kt
  app/src/main/res/layout/activity_login.xml
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  keystore/debug.keystore
  settings.gradle
Labels: feature :bulb:

#16 [feature/#14] Util 확장함수 모아놓은 core 모듈 만들기
  app/build.gradle.kts
  app/src/main/java/com/teamfillin/fillin/App.kt
  app/src/main/java/com/teamfillin/fillin/config/di/SingletonModule.kt
  app/src/main/java/com/teamfillin/fillin/design/ResolutionMetrics.kt
  app/src/main/java/com/teamfillin/fillin/presentation/login/LoginActivity.kt
  app/src/main/res/layout/activity_login.xml
  core/.gitignore
  core/build.gradle.kts
  core/consumer-rules.pro
  core/proguard-rules.pro
  core/src/androidTest/java/com/teamfillin/fillin/core/ExampleInstrumentedTest.kt
  core/src/main/AndroidManifest.xml
  core/src/main/java/com/teamfillin/fillin/core/base/BindingActivity.kt
  core/src/main/java/com/teamfillin/fillin/core/base/BindingFragment.kt
  core/src/main/java/com/teamfillin/fillin/core/content/BitmapRequestBody.kt
  core/src/main/java/com/teamfillin/fillin/core/content/ContentUriRequestBody.kt
  core/src/main/java/com/teamfillin/fillin/core/context/ContextExt.kt
  core/src/main/java/com/teamfillin/fillin/core/design/StatusBar.kt
  core/src/main/java/com/teamfillin/fillin/core/fragment/FragmentExt.kt
  core/src/main/java/com/teamfillin/fillin/core/intent/ArgsExt.kt
  core/src/main/java/com/teamfillin/fillin/core/intent/ExtraExt.kt
  core/src/main/java/com/teamfillin/fillin/core/view/ViewExt.kt
  core/src/test/java/com/teamfillin/fillin/core/ExampleUnitTest.kt
  settings.gradle
Labels: feature :bulb:

#23 [feature/#18] 지도 검색 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamfillin/fillin/data/ResponseLocationInfo.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/CustomDecoration.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/LocationListAdapter.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/MapSearchActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/StudioMapActivity.kt
  app/src/main/res/drawable/ic_clear.xml
  app/src/main/res/drawable/ic_place_small.xml
  app/src/main/res/layout/activity_map_search.xml
  app/src/main/res/layout/item_location_info.xml
Labels: feature :bulb:, 강민 🦖

#24 [feature/#22] 소셜 로그인/회원가입 구현
  app/src/debug/java/com/teamfillin/fillin/FlipperInitializer.kt
  app/src/main/java/com/teamfillin/fillin/config/di/RepositoryModule.kt
  app/src/main/java/com/teamfillin/fillin/config/di/RetrofitModule.kt
  app/src/main/java/com/teamfillin/fillin/config/di/ServiceModule.kt
  app/src/main/java/com/teamfillin/fillin/config/di/SingletonModule.kt
  app/src/main/java/com/teamfillin/fillin/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/teamfillin/fillin/data/local/FillInDataStore.kt
  app/src/main/java/com/teamfillin/fillin/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/teamfillin/fillin/data/response/BaseResponse.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseAuth.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseRefresh.kt
  app/src/main/java/com/teamfillin/fillin/data/service/AuthService.kt
  app/src/main/java/com/teamfillin/fillin/domain/entity/Auth.kt
  app/src/main/java/com/teamfillin/fillin/domain/repository/AuthRepository.kt
  app/src/main/java/com/teamfillin/fillin/presentation/login/LoginActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/login/LoginViewModel.kt
Labels: feature :bulb:, 누누 ⛄️

#26 [feature/#20] 다이얼로그 구현
  app/src/main/AndroidManifest.xml
  app/src/main/ic_close22-playstore.png
  app/src/main/java/com/teamfillin/fillin/presentation/dialog/PhotoDialogFragment.kt
  app/src/main/java/com/teamfillin/fillin/presentation/home/HomeActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/home/HomeMultiMode.kt
  app/src/main/java/com/teamfillin/fillin/presentation/home/NewPhotosAdapter.kt
  app/src/main/java/com/teamfillin/fillin/presentation/home/NewPhotosData.kt
  app/src/main/res/drawable-hdpi/and_photo_rectangle.png
  app/src/main/res/drawable-hdpi/and_photoframe.png
  app/src/main/res/drawable-mdpi/and_photo_rectangle.png
  app/src/main/res/drawable-mdpi/and_photoframe.png
  app/src/main/res/drawable-v24/like.png
  app/src/main/res/drawable-v24/unlike.png
  app/src/main/res/drawable-xhdpi/and_photo_rectangle.png
  app/src/main/res/drawable-xhdpi/and_photoframe.png
  app/src/main/res/drawable-xxhdpi/and_photo_rectangle.png
  app/src/main/res/drawable-xxhdpi/and_photoframe.png
  app/src/main/res/drawable-xxxhdpi/and_photo_rectangle.png
  app/src/main/res/drawable-xxxhdpi/and_photoframe.png
  app/src/main/res/drawable/heartbutton.xml
  app/src/main/res/drawable/ic_basic_profile.xml
  app/src/main/res/drawable/ic_btn_like.xml
  app/src/main/res/drawable/ic_btn_unlike.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_dialog_clear.xml
  app/src/main/res/drawable/ic_filmroll_small.xml
  app/src/main/res/drawable/ic_heart.xml
  app/src/main/res/drawable/ic_home_addphoto.xml
  app/src/main/res/drawable/ic_icn_heart.xml
  app/src/main/res/drawable/ic_next.xml
  app/src/main/res/drawable/ic_red_heart.xml
  app/src/main/res/drawable/layout_line.xml
  app/src/main/res/drawable/linearline.xml
  app/src/main/res/drawable/nextbutton.xml
  app/src/main/res/drawable/popup.xml
  app/src/main/res/font/noto_sans_kr.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_map_search.xml
  app/src/main/res/layout/activity_studio_map.xml
  app/src/main/res/layout/fragment_photo_dialog.xml
  app/src/main/res/layout/item_film_roll_pic.xml
  app/src/main/res/layout/item_location_info.xml
  app/src/main/res/layout/item_new_photos_list.xml
  app/src/main/res/layout/item_next_button.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/fonts.xml
  app/src/main/res/values/strings.xml
Labels: 수빈🍍

#29 [feature/#25] 지도 바텀시트 구현
  app/src/main/java/com/teamfillin/fillin/data/ResponsePhotoReviewInfo.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/MapSearchActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/PhotoReviewListAdapter.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/StudioMapActivity.kt
  app/src/main/res/drawable/ic_call.xml
  app/src/main/res/drawable/ic_link.xml
  app/src/main/res/drawable/ic_place_select.xml
  app/src/main/res/drawable/ic_price.xml
  app/src/main/res/drawable/ic_scrap.xml
  app/src/main/res/drawable/ic_time.xml
  app/src/main/res/layout/activity_map_search.xml
  app/src/main/res/layout/activity_studio_map.xml
  app/src/main/res/layout/item_location_info.xml
  app/src/main/res/layout/item_photo_review.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature :bulb:, 강민 🦖

#28 [feature/#19] 사진업로드 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamfillin/fillin/presentation/AddCancelDialog.kt
  app/src/main/java/com/teamfillin/fillin/presentation/AddCompleteDialog.kt
  app/src/main/java/com/teamfillin/fillin/presentation/AddPhotoActivity.kt
  app/src/main/res/drawable/ic_icn_close.xml
  app/src/main/res/drawable/ic_img_photo.xml
  app/src/main/res/drawable/ic_img_trash.xml
  app/src/main/res/drawable/shape_btn_darkgrey2.xml
  app/src/main/res/drawable/shape_btn_fillinred.xml
  app/src/main/res/layout/activity_add_photo.xml
  app/src/main/res/layout/activity_studio_map.xml
  app/src/main/res/layout/dialog_addphoto_cancel.xml
  app/src/main/res/layout/dialog_addphoto_complete.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature :bulb:, 현지 🛌🏻

#33 [Feature/#32] 스튜디오 맵 전체 스튜디오 서버 통신
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamfillin/fillin/config/di/ServiceModule.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseLocationInfo.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponsePhotoReviewInfo.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseStudioInfo.kt
  app/src/main/java/com/teamfillin/fillin/data/service/StudioService.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/LocationListAdapter.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/MapSearchActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/PhotoReviewListAdapter.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/StudioMapActivity.kt
  app/src/main/res/layout/item_location_info.xml
  buildSrc/src/main/kotlin/Versions.kt
Labels: feature :bulb:, 강민 🦖

#36 [feature/#35] Splash 화면 구현 및 앱 로고/이름 설정
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/teamfillin/fillin/presentation/home/HomeActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/login/LoginActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_fillin_logo.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
Labels: feature :bulb:, 누누 ⛄️

#39 [feature/#37] 로그인 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamfillin/fillin/App.kt
  app/src/main/java/com/teamfillin/fillin/presentation/home/HomeActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/login/LoginActivity.kt
  app/src/main/res/drawable/ic_icn_kakao.xml
  app/src/main/res/drawable/shape_kakao_background.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature :bulb:, 누누 ⛄️

#43 [feature/#41] 온보딩 뷰/기능 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamfillin/fillin/data/local/FillInDataStore.kt
  app/src/main/java/com/teamfillin/fillin/presentation/login/LoginActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/onboarding/OnboardingActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/onboarding/OnboardingAdapter.kt
  app/src/main/res/drawable/ic_onboarding_1.xml
  app/src/main/res/drawable/ic_onboarding_2.xml
  app/src/main/res/drawable/ic_onboarding_3.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/item_onboarding.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
Labels: feature :bulb:, 누누 ⛄️

#49 [feature/fix_login] 로그인 api 수정된 것 반영
  app/src/main/java/com/teamfillin/fillin/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/teamfillin/fillin/data/service/AuthService.kt
  app/src/main/java/com/teamfillin/fillin/domain/repository/AuthRepository.kt
  app/src/main/java/com/teamfillin/fillin/presentation/login/KakaoAuthService.kt
  app/src/main/java/com/teamfillin/fillin/presentation/login/LoginActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/login/LoginViewModel.kt
Labels: refactor :recycle:, 누누 ⛄️

#50 [Feature/#47] 스튜디오 맵 완료
  app/src/main/java/com/teamfillin/fillin/data/response/ResponsePhotoReviewInfo.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseSearch.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseStudio.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseStudioLocation.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseStudioPhoto.kt
  app/src/main/java/com/teamfillin/fillin/data/service/HomeService.kt
  app/src/main/java/com/teamfillin/fillin/data/service/StudioService.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/MapSearchActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/PhotoReviewListAdapter.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/SearchListAdapter.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/SpaceDecoration.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/StudioMapActivity.kt
  app/src/main/res/layout/activity_map_search.xml
  app/src/main/res/layout/activity_studio_map.xml
  app/src/main/res/layout/item_location_info.xml
  app/src/main/res/layout/item_photo_review.xml
Labels: feature :bulb:, 강민 🦖

#52 [feature/#51] 홈 화면 미니 맵 구현
  app/src/main/java/com/teamfillin/fillin/presentation/home/HomeActivity.kt
  app/src/main/res/layout/activity_home.xml
Labels: feature :bulb:, 강민 🦖

#54 [Feature/#53] 지도 포토 리뷰 다이얼로그 구현
  app/src/main/java/com/teamfillin/fillin/presentation/dialog/PhotoDialogFragment.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/PhotoReviewListAdapter.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/StudioMapActivity.kt
  app/src/main/res/layout/fragment_photo_dialog.xml
Labels: feature :bulb:, 강민 🦖

#56 [Feature/#55] 필름 카테고리 서버 통신
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseFilmType.kt
  app/src/main/java/com/teamfillin/fillin/data/service/FilmStyleService.kt
  app/src/main/java/com/teamfillin/fillin/presentation/category/FilmCategoryAdapter.kt
  app/src/main/java/com/teamfillin/fillin/presentation/category/FilmRollCategoryActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/FilmRollActivity.kt
  app/src/main/res/layout/item_category_info.xml
Labels: feature :bulb:, 강민 🦖

#46 [Feature/#27] 필름롤 , 카테고리 뷰 코드리뷰 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamfillin/fillin/config/di/ServiceModule.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseFilmPhotoInfo.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseFilmRoll.kt
  app/src/main/java/com/teamfillin/fillin/data/service/CurationService.kt
  app/src/main/java/com/teamfillin/fillin/data/service/FilmPhotoService.kt
  app/src/main/java/com/teamfillin/fillin/data/service/FilmRollService.kt
  app/src/main/java/com/teamfillin/fillin/data/service/FilmStyleService.kt
  app/src/main/java/com/teamfillin/fillin/presentation/dialog/PhotoDialogFragment.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/CurationAdapter.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/FilmRollActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/FilmRollMultiMode.kt
  app/src/main/java/com/teamfillin/fillin/presentation/home/HomeActivity.kt
Labels: feature :bulb:, 수빈🍍

#59 [feature/image_experiment] 사진 등록 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamfillin/fillin/config/di/RepositoryModule.kt
  app/src/main/java/com/teamfillin/fillin/data/service/FilmRollService.kt
  app/src/main/java/com/teamfillin/fillin/data/service/HomeService.kt
  app/src/main/java/com/teamfillin/fillin/presentation/AddPhotoActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/category/FilmRollCategoryActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/CurationAdapter.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/FilmCategoryImageActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/FilmRollActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/add/AddCancelDialog.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/add/AddCompleteDialog.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/add/AddPhotoActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/add/AddPhotoViewModel.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/add/repository/AddPhotoRepository.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/add/repository/AddPhotoRepositoryImpl.kt
  app/src/main/java/com/teamfillin/fillin/presentation/home/HomeActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/MapSearchActivity.kt
  app/src/main/res/layout/activity_add_photo.xml
  app/src/main/res/layout/dialog_addphoto_cancel.xml
  app/src/main/res/layout/item_curation.xml
  core/src/main/java/com/teamfillin/fillin/core/content/ContentUriRequestBody.kt
Labels: feature :bulb:, 누누 ⛄️

#58 Feature/#38
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamfillin/fillin/MyPagePhotoRecyclerViewAdapter.kt
  app/src/main/java/com/teamfillin/fillin/Photos.kt
  app/src/main/java/com/teamfillin/fillin/RetrofitUtil.kt
  app/src/main/java/com/teamfillin/fillin/config/di/RetrofitModule.kt
  app/src/main/java/com/teamfillin/fillin/config/di/ServiceModule.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseUserInfo.kt
  app/src/main/java/com/teamfillin/fillin/data/response/ResponseUserPhotoInfo.kt
  app/src/main/java/com/teamfillin/fillin/data/service/MyPagePhotoService.kt
  app/src/main/java/com/teamfillin/fillin/data/service/UserService.kt
  app/src/main/java/com/teamfillin/fillin/presentation/MyPageActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/home/HomeActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/home/NewPhotosAdapter.kt
  app/src/main/java/com/teamfillin/fillin/presentation/map/StudioMapActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/my/MyPageActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/my/MyPagePhotoRecyclerViewAdapter.kt
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_my_page.xml
  app/src/main/res/layout/item_my_page.xml
  app/src/main/res/values/strings.xml
Labels: feature :bulb:, 강민 🦖, 현지 🛌🏻

#61 [feature/#60] 서버 오류 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamfillin/fillin/presentation/home/HomeActivity.kt
Labels: feature :bulb:, 강민 🦖

#45 [feature/paging_expermiental] 무한스크롤 구현 예시
  app/build.gradle.kts
  app/src/main/java/com/teamfillin/fillin/config/di/RepositoryModule.kt
  app/src/main/java/com/teamfillin/fillin/config/di/ServiceModule.kt
  app/src/main/java/com/teamfillin/fillin/data/remote/CategoryPhotosPagingSource.kt
  app/src/main/java/com/teamfillin/fillin/data/remote/PhotosPagingSource.kt
  app/src/main/java/com/teamfillin/fillin/data/repository/PhotoPagingRepository.kt
  app/src/main/java/com/teamfillin/fillin/data/response/experimental/PhotoDto.kt
  app/src/main/java/com/teamfillin/fillin/data/service/PagingService.kt
  app/src/main/java/com/teamfillin/fillin/domain/entity/Photo.kt
  app/src/main/java/com/teamfillin/fillin/presentation/dialog/PhotoDialogFragment.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/FilmCategoryImageActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/FilmCategoryViewModel.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/FilmImageAdapter.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/FilmRollActivity.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/FilmRollAdapter.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/FilmRollPagingAdapter.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/FilmRollViewModel.kt
  app/src/main/java/com/teamfillin/fillin/presentation/filmroll/model/PhotoUiModel.kt
  app/src/main/res/layout/activity_category_image.xml
  app/src/main/res/layout/activity_film_roll.xml
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  core/build.gradle.kts
  core/src/main/java/com/teamfillin/fillin/core/base/OffsetPagingSource.kt
  core/src/main/java/com/teamfillin/fillin/core/view/ViewExt.kt
Labels: feature :bulb:, 누누 ⛄️
